### PR TITLE
Python MkII (python_nx) and the code from the SCO PR Rixxan has submitted/

### PR DESCRIPTION
**Pull request by alex-williams**
Known issues:
- FSD Range is anywhere from 0.01 - 0.03LY out on Min/Max Estimates with a SCO FSD (I think this is a rounding issue and Coriolis already did this?)
- FSD Range goes WAY out when you engineer the FSD, Coriolis thinks you should have a LOT more range than you get in game... I do not yet know why this is.
- EDDBID Value for the ship is made up, as there is no EDDBID for this ship

### CODE REVIEW

**Comment by felixlinker** [comment]
Hey Alex! Thanks for putting in the work to improve coriolis. If I get the title of your PR right, you include the same changes as #98. This is not ideal for merging. Could you change your code s.t. you only include new changes?

Also, you list a number of known issues. Do these issues apply to coriolis already or are they specific to your PR? If they are issues of coriolis, please open an issue. If they are specific to your PR: Could you fix them so that I wait before accepting your PR? Thanks!

**Comment by alex-williams** [comment]
> Hey Alex! Thanks for putting in the work to improve coriolis. If I get the title of your PR right, you include the same changes as #98. This is not ideal for merging. Could you change your code s.t. you only include new changes?
> 

This is done.

> Also, you list a number of known issues. Do these issues apply to coriolis already or are they specific to your PR? If they are issues of coriolis, please open an issue. If they are specific to your PR: Could you fix them so that I wait before accepting your PR? Thanks!

I currently cannot find the reason for the engineering values going crazy on the SCO drives. Technically, it's an issue with PR #98, as opposed to this PR, because it's an issue with engineering the SCO drives. If you could accept both PR's so that the PyMkII and the SCO drives both go in, I can do further testing and submit further PR's to fix the problem if/when I find the issues causing them.

**Comment by felixlinker** [comment]
Final ask: Could you change the EDDB IDs that you made up to `0` that way, it's a bit clearer that they're made up.

If the issues you described are specific to the SCO drives, I'm happy to merge this PR!

Just a sidenote: Testing changes does not depend on me merging them :) You can fire up coriolis locally on your machine. Instructions for that should be in the coriolis repo! If they're not clear to you/don't work, would be great to let me know on Discord so that we can improve them!

**Comment by bengels00** [comment]
Is a dev-website with the EDCD:develop code online so we can test?

**Comment by felixlinker** [comment]
Yes. It is live at https://beta.coriolis.io

But you do not require this. I would advise everyone to run coriolis locally. This also helps with debugging. You can find instructions on how to do that here: https://github.com/EDCD/coriolis?tab=readme-ov-file#development

**Pull request merged**
