### PR TITLE
[WIP] [No merge till beta] Add Alliance Chieftan

### PR DESCRIPTION
**Pull request by willyb321**
Do not merge until at least beta (25th)

Adds the Alliance Chieftan

### CODE REVIEW

**Comment by willyb321** [comment]
Should be right to merge to beta @strideynet

**Comment by joshlcampbell** [comment]
Do you know if the chieftain is Horizons-only? Haven't had time to download and play it myself yet. If so, could you add the following to the ship's JSON?

```json
"requirements": {
    "horizons": true
},
```

Can look at the Beluga or Dolphin files for reference. That should ensure the "Horizons" icon shows up next to the ship's name on the outfitting page (my one and only contribution thus far).

**Comment by willyb321** [comment]
@joshlcampbell yep, it is horizons only. Will add. Thanks

**Comment by joshlcampbell** [comment]
@willyb321 Awesome :) Thanks

**Pull request merged**
